---
  - name: install apache webserver(play1)
   host: all
   become: true
   task:
   - name: install apache
     ansible.builtin.apt:
       name: apache2
       state: present
   - name: Create a directory if it does not exist
     ansible.builtin.file: 
       path: /home/vagrant
       state: directory

  - name: create a file (play2)
    hosts: node1
    become: true
    tasks:
    - name: create a file called jerome
      ansible.builtin.file:
      path: Desktop/Workspace/Anne
      state: touch 



